version: '3.8'

services:
  db:
    image: postgres:11
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data

  db-tests:
    image: postgres:11
    restart: always
    ports:
      - ${DB_TESTS_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:alpine
    command: redis-server
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ${REDIS_VOLUME}:/data